version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: clean.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: app_stop.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: app_start.sh
      timeout: 10
      runas: root
  ValidateService:
    - location: vld_app.sh
      timeout: 30
      runas: root
