version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y npm
      - sudo npm install -g @angular/cli
  pre_build:
    commands:
      - rm -rf .git README.md
      - npm install
  build:
    commands:
      - ng build
  post_build:
    commands:
      - ls -a
      - cp ./scripts/* ./dist/
artifacts:
  files:
    - 'dist/**/*'
  name: sample-ng-app-$(date +%Y-%m-%d)
  discard-paths: yes
