version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y npm
      - sudo npm install -g @angular/cli
  pre_build:
    commands:
      - rm -rf .git README.md
      - npm install
  build:
    commands:
      - ng build
artifacts:
  files:
    - 'dist/*'
  name: myname-$(date +%Y-%m-%d)
  base-directory: dist
  discard-paths: yes